---
# tasks file for pirpedro.raspbian
- name: 'Configure WIFI'
  template: src=wpa_supplicant.conf.j2 dest=/etc/wpa_supplicant/wpa_supplicant.conf mode=0600
  become: yes
  tags: network, wifi
#  notify: restart
